// Code generated by protoc-gen-go. DO NOT EDIT.
// source: zzz.proto

package zzz

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	AccountName          string   `protobuf:"bytes,1,opt,name=accountName,proto3" json:"accountName,omitempty"`
	Pwd                  string   `protobuf:"bytes,2,opt,name=pwd,proto3" json:"pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_b620e5f2f27f9a13, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *Account) GetPwd() string {
	if m != nil {
		return m.Pwd
	}
	return ""
}

type AccountList struct {
	Index                int32      `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	List                 []*Account `protobuf:"bytes,2,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountList) Reset()         { *m = AccountList{} }
func (m *AccountList) String() string { return proto.CompactTextString(m) }
func (*AccountList) ProtoMessage()    {}
func (*AccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b620e5f2f27f9a13, []int{1}
}

func (m *AccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountList.Unmarshal(m, b)
}
func (m *AccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountList.Marshal(b, m, deterministic)
}
func (m *AccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountList.Merge(m, src)
}
func (m *AccountList) XXX_Size() int {
	return xxx_messageInfo_AccountList.Size(m)
}
func (m *AccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountList.DiscardUnknown(m)
}

var xxx_messageInfo_AccountList proto.InternalMessageInfo

func (m *AccountList) GetIndex() int32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *AccountList) GetList() []*Account {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*Account)(nil), "zzz.Account")
	proto.RegisterType((*AccountList)(nil), "zzz.AccountList")
}

func init() { proto.RegisterFile("zzz.proto", fileDescriptor_b620e5f2f27f9a13) }

var fileDescriptor_b620e5f2f27f9a13 = []byte{
	// 142 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xac, 0xaa, 0xaa, 0xd2,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xae, 0xaa, 0xaa, 0x52, 0xb2, 0xe5, 0x62, 0x77, 0x4c,
	0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0x11, 0x52, 0xe0, 0xe2, 0x4e, 0x84, 0x30, 0xfd, 0x12, 0x73, 0x53,
	0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x90, 0x85, 0x84, 0x04, 0xb8, 0x98, 0x0b, 0xca, 0x53,
	0x24, 0x98, 0xc0, 0x32, 0x20, 0xa6, 0x92, 0x2b, 0x17, 0x37, 0x54, 0xbb, 0x4f, 0x66, 0x71, 0x89,
	0x90, 0x08, 0x17, 0x6b, 0x66, 0x5e, 0x4a, 0x6a, 0x05, 0x58, 0x33, 0x6b, 0x10, 0x84, 0x23, 0xa4,
	0xc0, 0xc5, 0x92, 0x93, 0x59, 0x5c, 0x22, 0xc1, 0xa4, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xa3, 0x07,
	0x72, 0x02, 0x54, 0x57, 0x10, 0x58, 0xc6, 0x89, 0xc9, 0x83, 0x39, 0x89, 0x0d, 0xec, 0x2a, 0x63,
	0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6a, 0x3a, 0xd9, 0x4b, 0xa2, 0x00, 0x00, 0x00,
}
