name: Node CI

on: [push]

jobs:
  publish:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v1
    - name: Decrypt large secret
      env:
          LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}           
      run: |          
           ./scripts/decrypt_secret.sh
    - name: Test printing your secret (Remove this step in production)
      run: |          
           cat $HOME/secrets/my_secret.json               
    - name: publish
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN}}
      run: |
        . $HOME/secrets/my_secret.sh        
        echo "ccc" ${x}                   
        echo "ccc" ${y}           
        cat $HOME/secrets/my_secret.json 
        echo $CI
        echo export NPM_TOKEN=${NPM_TOKEN} >> ~/.profile
        echo //registry.npmjs.org/:_authToken=$NPM_TOKEN >> ~/.npmrc
        source ~/.profile
        npm publish
        #npm ci
        #npm run build --if-present
        #npm test
